namespace Eu4HackGUI.Controls
{
    partial class HackControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.Run = new System.Windows.Forms.Button();
            this.TypeCheckListBox = new System.Windows.Forms.CheckedListBox();
            this.SelectedTypesLabel = new System.Windows.Forms.Label();
            this.SelectedCountry = new System.Windows.Forms.Label();
            this.SearchCountry = new System.Windows.Forms.TextBox();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.SuspendLayout();
            // 
            // Run
            // 
            this.Run.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.Run.Dock = System.Windows.Forms.DockStyle.Top;
            this.Run.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.Run.FlatAppearance.BorderSize = 0;
            this.Run.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.Run.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.Run.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.Run.ForeColor = System.Drawing.Color.DarkGray;
            this.Run.Location = new System.Drawing.Point(0, 23);
            this.Run.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Run.Name = "Run";
            this.Run.Size = new System.Drawing.Size(399, 29);
            this.Run.TabIndex = 0;
            this.Run.Text = "Run";
            this.Run.UseVisualStyleBackColor = false;
            // 
            // TypeCheckListBox
            // 
            this.TypeCheckListBox.BackColor = System.Drawing.Color.Black;
            this.TypeCheckListBox.CheckOnClick = true;
            this.TypeCheckListBox.Dock = System.Windows.Forms.DockStyle.Left;
            this.TypeCheckListBox.ForeColor = System.Drawing.Color.DarkGray;
            this.TypeCheckListBox.FormattingEnabled = true;
            this.TypeCheckListBox.Items.AddRange(new object[] {
            "Country_Ideas",
            "Provinces",
            "Countries"});
            this.TypeCheckListBox.Location = new System.Drawing.Point(0, 0);
            this.TypeCheckListBox.Name = "TypeCheckListBox";
            this.TypeCheckListBox.Size = new System.Drawing.Size(231, 400);
            this.TypeCheckListBox.TabIndex = 1;
            // 
            // SelectedTypesLabel
            // 
            this.SelectedTypesLabel.AutoSize = true;
            this.SelectedTypesLabel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.SelectedTypesLabel.ForeColor = System.Drawing.Color.DimGray;
            this.SelectedTypesLabel.Location = new System.Drawing.Point(0, 370);
            this.SelectedTypesLabel.Margin = new System.Windows.Forms.Padding(3);
            this.SelectedTypesLabel.Name = "SelectedTypesLabel";
            this.SelectedTypesLabel.Size = new System.Drawing.Size(83, 15);
            this.SelectedTypesLabel.TabIndex = 2;
            this.SelectedTypesLabel.Text = "None Selected";
            // 
            // SelectedCountry
            // 
            this.SelectedCountry.AutoSize = true;
            this.SelectedCountry.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.SelectedCountry.ForeColor = System.Drawing.Color.DimGray;
            this.SelectedCountry.Location = new System.Drawing.Point(0, 385);
            this.SelectedCountry.Margin = new System.Windows.Forms.Padding(3);
            this.SelectedCountry.Name = "SelectedCountry";
            this.SelectedCountry.Size = new System.Drawing.Size(97, 15);
            this.SelectedCountry.TabIndex = 2;
            this.SelectedCountry.Text = "Selected Country";
            // 
            // SearchCountry
            // 
            this.SearchCountry.AutoCompleteCustomSource.AddRange(new string[] {
            "Sweden",
            "Denmark",
            "Finland",
            "Gotland",
            "Norway",
            "Holstein",
            "Scandinavia",
            "Estonia",
            "Livonia",
            "Sapmi",
            "Karelia",
            "Iceland",
            "Achaea",
            "Albania",
            "Athens",
            "Bosnia",
            "Bulgaria",
            "Byzantium",
            "Corfu",
            "Croatia",
            "Crete",
            "Cyprus",
            "Dalmatia",
            "Epirus",
            "Greece",
            "The Knights",
            "Morea",
            "Moldavia",
            "Montenegro",
            "Naxos",
            "Ragusa",
            "Romania",
            "Serbia",
            "Transylvania",
            "Wallachia",
            "Hungary",
            "Nitra",
            "Ottomans",
            "Clanricarde",
            "Cornwall",
            "England",
            "Leinster",
            "Ireland",
            "Thomond",
            "Scotland",
            "Tyrone",
            "Wales",
            "Northumberland",
            "Great Britain",
            "Meath",
            "Ulster",
            "Desmond",
            "Sligo",
            "Kildare",
            "Gaeldom",
            "Ormond",
            "Tyrconnell",
            "Offaly",
            "Munster",
            "Mann",
            "The Isles",
            "Brazil",
            "Canada",
            "Chile",
            "Colombia",
            "Haiti",
            "La Plata",
            "Louisiana",
            "Mexico",
            "Peru",
            "Paraguay",
            "Quebec",
            "United Central America",
            "United States",
            "Venezuela",
            "Australia",
            "California",
            "Texas",
            "Cascadia",
            "Alaska",
            "Zealandia",
            "Illinois",
            "Florida",
            "Vermont",
            "Sonora",
            "West Indies",
            "Cuba",
            "Danzig",
            "Krakow",
            "Lithuania",
            "Livonian Order",
            "Mazovia",
            "Poland",
            "Prussia",
            "Kurland",
            "Riga",
            "Teutonic Order",
            "Commonwealth",
            "Galicia–Volhynia",
            "Kiev",
            "Chernigov",
            "Odoyev",
            "Alençon",
            "Strasbourg",
            "Armagnac",
            "Auvergne",
            "Avignon",
            "Bourbonnais",
            "Brittany",
            "Burgundy",
            "Champagne",
            "Corsica",
            "Dauphine",
            "Foix",
            "France",
            "Gascony",
            "Nevers",
            "Normandy",
            "Orleans",
            "Picardy",
            "Provence",
            "Sardinia-Piedmont",
            "Toulouse",
            "Berry",
            "Aachen",
            "Anhalt",
            "Ansbach",
            "Augsburg",
            "Baden",
            "Bavaria",
            "Bohemia",
            "Brandenburg",
            "Bremen",
            "Brunswick",
            "East Frisia",
            "Frankfurt",
            "Germany",
            "Austria",
            "Hamburg",
            "Hanover",
            "Hesse",
            "Holy Roman Empire",
            "Cleves",
            "Cologne",
            "Saxe-Lauenburg",
            "Lorraine",
            "Lüneburg",
            "Magdeburg",
            "Mainz",
            "Meissen",
            "Mecklenburg",
            "Münster",
            "Moravia",
            "Oldenburg",
            "The Palatinate",
            "Pomerania",
            "Saxony",
            "Silesia",
            "Salzburg",
            "Styria",
            "Switzerland",
            "Thuringia",
            "Tirol",
            "Trier",
            "Ulm",
            "Wurzburg",
            "Westphalia",
            "Wurttemberg",
            "Nuremberg",
            "Memmingen",
            "Verden",
            "Nassau",
            "Dortmund",
            "Dithmarschen",
            "Aragon",
            "Castile",
            "Catalonia",
            "Granada",
            "Navarra",
            "Portugal",
            "Spain",
            "Galicia",
            "León",
            "Andalusia",
            "Valencia",
            "Asturias",
            "Majorca",
            "Aquileia",
            "Etruria",
            "Ferrara",
            "Genoa",
            "Italy",
            "Mantua",
            "Milan",
            "Modena",
            "Naples",
            "The Papal State",
            "Parma",
            "Pisa",
            "Sardinia",
            "Savoy",
            "Sicily",
            "Siena",
            "Tuscany",
            "Urbino",
            "Venice",
            "Montferrat",
            "Lucca",
            "Florence",
            "Malta",
            "Brabant",
            "Flanders",
            "Friesland",
            "Gelre",
            "Hainaut",
            "Holland",
            "Liege",
            "Luxembourg",
            "Netherlands",
            "Utrecht",
            "Armenia",
            "Astrakhan",
            "Crimea",
            "Georgia",
            "Kazan",
            "Muscovy",
            "Novgorod",
            "Pskov",
            "Qasim",
            "Russia",
            "Ryazan",
            "Tver",
            "Ruthenia",
            "Yaroslavl",
            "Zaporozhie",
            "Nogai",
            "Sibir",
            "Polotsk",
            "Perm",
            "Theodoro",
            "Bashkiria",
            "Beloozero",
            "Rostov",
            "Great Horde",
            "Golden Horde",
            "Aden",
            "Haasa",
            "Anizah",
            "Arabia",
            "Ardalan",
            "Soran",
            "Dawasir",
            "Eretna",
            "Fadl",
            "Germiyan",
            "Hadramut",
            "Hejaz",
            "Lebanon",
            "Makuria",
            "Medina",
            "Mikhlaf",
            "Mahra",
            "Najd",
            "Najran",
            "Oman",
            "Rassids",
            "Shammar",
            "Sharjah",
            "Shirvan",
            "Yas",
            "Yemen",
            "Hisn Kayfa",
            "Bitlis",
            "Aq Qoyunlu",
            "Aydin",
            "Candar",
            "Dulkadir",
            "Iraq",
            "Karaman",
            "Syria",
            "Trebizond",
            "Saruhan",
            "Mentese",
            "Ramazan",
            "Avaria",
            "Kharabakh",
            "Samtskhe",
            "Ardabil",
            "Mushasha",
            "Rûm",
            "Algiers",
            "Fez",
            "Mamluks",
            "Morocco",
            "Tripoli",
            "Tunis",
            "Egypt",
            "Kabylia",
            "Tafilalt",
            "Sus",
            "Tlemcen",
            "Touggourt",
            "Djerid",
            "Fezzan",
            "Mzab",
            "Salé",
            "Tétouan",
            "Marrakesh",
            "Kazakh",
            "Khiva",
            "Uzbek",
            "Ferghana",
            "Bukhara",
            "Afghanistan",
            "Khorasan",
            "Persia",
            "Qara Qoyunlu",
            "Timurids",
            "Transoxiana",
            "Gilan",
            "Circassia",
            "Gazikumukh",
            "Imereti",
            "Mazandaran",
            "Hormuz",
            "Luristan",
            "Sistan",
            "Biapas",
            "Fars",
            "Kerman",
            "Yazd",
            "Isfahan",
            "Tabriz",
            "Basra",
            "Maregheh",
            "Ajam",
            "Aztec",
            "Cherokee",
            "Chimu",
            "Creek",
            "Huron",
            "Inca",
            "Iroquois",
            "Maya",
            "Shawnee",
            "Zapotec",
            "Ashanti",
            "Benin",
            "Ethiopia",
            "Kongo",
            "Mali",
            "Funj",
            "Songhai",
            "Kilwa",
            "Mutapa",
            "Adal",
            "Hausa",
            "Kanem Bornu",
            "Loango",
            "Oyo",
            "Segu",
            "Sokoto",
            "Jolof",
            "Sofala",
            "Mombasa",
            "Malindi",
            "Ajuuraan",
            "Mogadishu",
            "Ennarea",
            "Aussa",
            "Alodia",
            "Darfur",
            "Geledi",
            "Harar",
            "Hobyo",
            "Kaffa",
            "Medri Bahri",
            "Majeerteen",
            "Marehan",
            "Pate",
            "Warsangali",
            "Semien",
            "Beja",
            "Jimma",
            "Welayta",
            "Damot",
            "Hadiya",
            "Shewa",
            "Janjiro",
            "Dongola",
            "Tyo",
            "Soyo",
            "Kasanje",
            "Luba",
            "Lunda",
            "Chokwe",
            "Kikondja",
            "Kazembe",
            "Yaka",
            "Kalundwe",
            "Kuba",
            "Rwanda",
            "Burundi",
            "Buganda",
            "Nkore",
            "Karagwe",
            "Bunyoro",
            "Busoga",
            "Buha",
            "Maravi",
            "Lundu",
            "Tumbuka",
            "Makua",
            "Butua",
            "Imerina",
            "Sakalava",
            "Betsimisaraka",
            "Mahafaly",
            "Antemoro",
            "Annam",
            "Arakan",
            "Aceh",
            "Ayutthaya",
            "Bali",
            "Banten",
            "Brunei",
            "Champa",
            "Chagatai",
            "Champasak",
            "Dai Viet",
            "Japan",
            "Amago",
            "Asakura",
            "Chosokabe",
            "Date",
            "Hojo",
            "Hosokawa",
            "Hatakeyama",
            "Ikeda",
            "Imagawa",
            "Maeda",
            "Mori",
            "Oda",
            "Otomo",
            "Ouchi",
            "Shiba",
            "Shimazu",
            "Takeda",
            "Tokugawa",
            "Uesugi",
            "Yamana",
            "Nanbu",
            "Ashikaga",
            "Kitabatake",
            "Ainu",
            "Akamatsu",
            "Ando",
            "Chiba",
            "Isshiki",
            "Ito",
            "Kikuchi",
            "Kono",
            "Ogasawara",
            "Shoni",
            "Satake",
            "Toki",
            "Utsunomiya",
            "Tsutsui",
            "Mongolia",
            "Khmer",
            "Korea",
            "Lan Na",
            "Luang Prabang",
            "Lan Xang",
            "Majapahit",
            "Manchu",
            "Makassar",
            "Malacca",
            "Ming",
            "Mataram",
            "Oirat",
            "Pattani",
            "Pegu",
            "Qing",
            "Ryukyu",
            "Shan",
            "Sukhothai",
            "Sulu",
            "Taungu",
            "Tibet",
            "Tonkin",
            "Vientiane",
            "Zhou",
            "Shun",
            "Xi",
            "Yuan",
            "Tungning",
            "Ilkhanate",
            "Kalmyk",
            "Mongol Empire",
            "So",
            "Nivkh",
            "Solon",
            "Donghai",
            "Udege",
            "Yeren",
            "Haixi",
            "Jianzhou",
            "Korchin",
            "Khalkha",
            "Kara Del",
            "Dzungar",
            "Yarkand",
            "Chahar",
            "Khoshuud",
            "Sarig Yogir",
            "Tsang",
            "Kham",
            "Guge",
            "U",
            "Dali",
            "Yi",
            "Miao",
            "Min",
            "Yue",
            "Shu",
            "Ning",
            "Chu",
            "Tang",
            "Wu",
            "Qi",
            "Yan",
            "Jin",
            "Liang",
            "Qin",
            "Huai",
            "Changsheng",
            "Baluchistan",
            "Bengal",
            "Bijapur",
            "Bahmanis",
            "Delhi",
            "Golkonda",
            "Deccan",
            "Marathas",
            "Mughals",
            "Mysore",
            "Vijayanagar",
            "Ahmednagar",
            "Assam",
            "Gujarat",
            "Jaunpur",
            "Madurai",
            "Malwa",
            "Marwar",
            "Mewar",
            "Multan",
            "Nagpur",
            "Nepal",
            "Orissa",
            "Punjab",
            "Sindh",
            "Berar",
            "Jangladesh",
            "Carnatic",
            "Garha",
            "Garjat",
            "Gwalior",
            "Dhundhar",
            "Kashmir",
            "Keladi",
            "Khandesh",
            "Oudh",
            "Venad",
            "Calicut",
            "Mewat",
            "Baroda",
            "Bastar",
            "Bhutan",
            "Bundelkhand",
            "Kotte",
            "Jaisalmer",
            "Kachar",
            "Koch",
            "Kangra",
            "Kutch",
            "Kochin",
            "Manipur",
            "Hadoti",
            "Nagaur",
            "Rohilkhand",
            "Ladakh",
            "Baghelkhand",
            "Jaffna",
            "Patiala",
            "Garhwal",
            "Chanda",
            "Jharkhand",
            "Habsan",
            "Tirhut",
            "Rewa Kantha",
            "Baglana",
            "Tripura",
            "Sadiya",
            "Bharat",
            "Andhra",
            "Maldives",
            "Bishnupur",
            "Sikkim",
            "Idar",
            "Jhalavad",
            "Palitana",
            "Navanagar",
            "Rajkot",
            "Junagarh",
            "Porbandar",
            "Kalinjar",
            "Kalpi",
            "Sambalpur",
            "Patna",
            "Ratanpur",
            "Kalahandi",
            "Keonhjar",
            "Parlakhimidi",
            "Jeypore",
            "Surguja",
            "Kandy",
            "Telingana",
            "Kolathunad",
            "Dang",
            "Doti",
            "Gorkha",
            "Jumla",
            "Limbuwan",
            "Makwanpur",
            "Sirmur",
            "Kathmandu",
            "Kumaon",
            "Gingee",
            "Tanjore",
            "Sirhind",
            "Rajputana",
            "Bar",
            "Lübeck",
            "Smolensk",
            "Nizhny Novgorod",
            "Jerusalem",
            "Malaya",
            "Hindustan",
            "Abenaki",
            "Apache",
            "Assiniboine",
            "Blackfoot",
            "Caddo",
            "Chickasaw",
            "Choctaw",
            "Cheyenne",
            "Comanche",
            "Fox",
            "Illiniwek",
            "Lenape",
            "Mahican",
            "Mikmaq",
            "Miami",
            "Navajo",
            "Ojibwe",
            "Osage",
            "Ottawa",
            "Pawnee",
            "Pequot",
            "Pima",
            "Potawatomi",
            "Powhatan",
            "Pueblo",
            "Shoshone",
            "Sioux",
            "Susquehannock",
            "Cree",
            "Air",
            "Bonoman",
            "Dahomey",
            "Dagbon",
            "Fulo",
            "Jenné",
            "Kano",
            "Kaabu",
            "Kong",
            "Katsina",
            "Mossi",
            "Nupe",
            "Timbuktu",
            "Yao",
            "Yatenga",
            "Macina",
            "Zazzau",
            "Ndongo",
            "Ava",
            "Hsenwi",
            "Johor",
            "Kedah",
            "Ligor",
            "Muan Phuang",
            "Mong Yang",
            "Perak",
            "Mong Mao",
            "Mong Kawng",
            "Mong Pai",
            "Mong Nai",
            "Kale",
            "Hsipaw",
            "Prome",
            "Chukchi",
            "Khodynt",
            "Chavchuveny",
            "Kamchadals",
            "Buryatia",
            "Arapaho",
            "Colima",
            "Chinook",
            "Cocomes",
            "Haida",
            "Itza",
            "Kiche",
            "Kiowa",
            "Mixtec",
            "Salish",
            "Tarascan",
            "Tlapanec",
            "Tlaxcala",
            "Totonac",
            "Wichita",
            "Xiu",
            "Blambangan",
            "Buton",
            "Cirebon",
            "Demak",
            "Pagarruyung",
            "Palembang",
            "Pasai",
            "Siak",
            "Sunda",
            "Kutai",
            "Banjar",
            "Lanfang",
            "Lanao",
            "Luwu",
            "Maguindanao",
            "Ternate",
            "Tidore",
            "Madyas",
            "Pangasinan",
            "Tondo",
            "Maynila",
            "Cebu",
            "Butuan",
            "Cusco",
            "Calchaqui",
            "Mapuche",
            "Muisca",
            "Quito",
            "Cajamarca",
            "Huyla",
            "Potiguara",
            "Tupiniquim",
            "Tupinamba",
            "Tapuia",
            "Guarani",
            "Charrua",
            "Wanka",
            "Chachapoya",
            "Colla",
            "Charca",
            "Pacajes",
            "Arawak",
            "Carib",
            "Ichma",
            "Matlatzinca",
            "Coixtlahuaca",
            "Teotitlan",
            "Xalisco",
            "Guamar",
            "Huastec",
            "Chichimeca",
            "Otomi",
            "Yokotan",
            "Tzotzil",
            "Kaqchikel",
            "Chactemal",
            "Keres",
            "Zuni",
            "Mescalero",
            "Lipan",
            "Chorti",
            "Miskito",
            "Tairona",
            "Can Pech",
            "Tonala",
            "Yaqui",
            "Yokuts",
            "New Providence",
            "Port Royal",
            "Tortuga",
            "Libertatia",
            "Munich",
            "Landshut",
            "Ingolstadt",
            "Passau",
            "Bregenz",
            "Konstanz",
            "Rothenburg",
            "Bayreuth",
            "Regensburg",
            "Geneva",
            "Three Leagues",
            "Opole",
            "Glogow",
            "Bologna",
            "Padua",
            "Saluzzo",
            "Spoleto",
            "Wolgast",
            "Stettin",
            "Goslar",
            "Lusatia",
            "Rügen",
            "Cilli",
            "Herzegovina",
            "Trent",
            "Berg",
            "Mulhouse",
            "Bamberg",
            "Ruppin",
            "Lippe",
            "Paderborn",
            "Calenberg",
            "Donauwörth",
            "Osnabrück",
            "Verona",
            "Coburg",
            "Lotharingia",
            "Perugia",
            "Two Sicilies",
            "Franconia",
            "Swabia",
            "Jan Mayen",
            "Roman Empire",
            "Synthetics",
            "Jomsvikings",
            "Hashashin",
            "Israel",
            "Knights Templar",
            "Trapalanda"});
            this.SearchCountry.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.SearchCountry.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.SearchCountry.BackColor = System.Drawing.Color.Black;
            this.SearchCountry.Dock = System.Windows.Forms.DockStyle.Top;
            this.SearchCountry.ForeColor = System.Drawing.Color.DarkGray;
            this.SearchCountry.Location = new System.Drawing.Point(0, 0);
            this.SearchCountry.Name = "SearchCountry";
            this.SearchCountry.Size = new System.Drawing.Size(399, 23);
            this.SearchCountry.TabIndex = 3;
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Margin = new System.Windows.Forms.Padding(0);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.TypeCheckListBox);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.Run);
            this.splitContainer1.Panel2.Controls.Add(this.SearchCountry);
            this.splitContainer1.Panel2.Controls.Add(this.SelectedTypesLabel);
            this.splitContainer1.Panel2.Controls.Add(this.SelectedCountry);
            this.splitContainer1.Size = new System.Drawing.Size(600, 400);
            this.splitContainer1.SplitterDistance = 200;
            this.splitContainer1.SplitterWidth = 1;
            this.splitContainer1.TabIndex = 4;
            // 
            // HackControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.BackColor = System.Drawing.Color.Black;
            this.Controls.Add(this.splitContainer1);
            this.MinimumSize = new System.Drawing.Size(150, 75);
            this.Name = "HackControl";
            this.Size = new System.Drawing.Size(600, 400);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button Run;
        private System.Windows.Forms.CheckedListBox TypeCheckListBox;
        private System.Windows.Forms.Label SelectedTypesLabel;
        private System.Windows.Forms.Label SelectedCountry;
        private System.Windows.Forms.TextBox SearchCountry;
        private System.Windows.Forms.SplitContainer splitContainer1;
    }
}
